# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R2Sx7BDlUDDa8H8UFXjDuvEy2xWT7hIj
"""

import matplotlib.pyplot as plt
#a=list(map(int, input("입력:").split()))
def res(a):
    mh=max(a)
    al=len(a)
    def ct(h):
        x=max(i for i in range(al) if a[i]>=h)
        n=min(i for i in range(al) if a[i]>=h)
        mid=len([ax for ax in a if ax>=h])
        return x-n-mid+1
    tot=0
    for j in range(mh+1):
       tot=tot+ct(j)
    return tot

#ex1: [3,2,1,1,2,3]
a=[3,2,1,1,2,3]
plt.bar(list(range(len(a))),a,width=1)
print("결과:", res(a))

#ex2: [0,1,0,2,1,0,1,3,2,1,2,1]
a=[0,1,0,2,1,0,1,3,2,1,2,1]
plt.bar(list(range(len(a))),a,width=1)
print("결과:", res(a))

#ex3: [3,1,3,1,3,1,3,1,2]
a=[3,1,3,1,3,1,3,1,2]
plt.bar(list(range(len(a))),a,width=1)
print("결과:", res(a))